"""Update Assessment module cascade to SET NULL

Revision ID: 0a7ae82b38f4
Revises: 597945333b63
Create Date: 2026-07-28 11:43:16.371170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '0a7ae82b38f4'
down_revision: Union[str, None] = '597945333b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assessment_module_id_fkey'), 'assessment', type_='foreignkey')
    op.create_foreign_key(None, 'assessment', 'campaign_module', ['module_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessment', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_module_id_fkey'), 'assessment', 'campaign_module', ['module_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
