"""add_saved_answers_and_timer

Revision ID: 32f89ea1894a
Revises: 8166162be4ed
Create Date: 2026-07-03 00:11:43.803157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32f89ea1894a'
down_revision: Union[str, None] = '8166162be4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('saved_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('assessment', sa.Column('time_remaining_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'time_remaining_seconds')
    op.drop_column('assessment', 'saved_answers')
    # ### end Alembic commands ###
