"""prep_phase_4_schema

Revision ID: 37187aed6f40
Revises: 9929a5bb7e0a
Create Date: 2026-07-11 12:13:15.577263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37187aed6f40'
down_revision: Union[str, None] = '9929a5bb7e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add Phase 4 analytics flag
    op.add_column('campaign_module', sa.Column('requires_remediation', sa.Boolean(), nullable=True, server_default='false'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('BLOCK_QUIZ', 'BLOCK_VIDEO', 'BLOCK_DOCUMENT_PDF', 'BLOCK_IMAGE', 'BLOCK_AUDIO', 'BLOCK_CUSTOM', name='blocktypeenum').create(op.get_bind())
    sa.Enum('PENDING', 'SUBMITTED', 'GRADED', 'LATE', 'NOT_SUBMITTED', name='assignmentusersubmissionstatus').create(op.get_bind())
    sa.Enum('FILE_SUBMISSION', 'QUIZ', 'FORM', 'CODE', 'SHORT_ANSWER', 'NUMBER_ANSWER', 'OTHER', name='assignmenttasktypeenum').create(op.get_bind())
    sa.Enum('ALPHABET', 'NUMERIC', 'PERCENTAGE', 'PASS_FAIL', 'GPA_SCALE', name='gradingtypeenum').create(op.get_bind())
    sa.Enum('IMAGE', 'VIDEO', 'BOTH', name='thumbnail_type').create(op.get_bind())
    sa.Enum('PUBLIC', 'AUTHENTICATED', 'RESTRICTED', name='locktype').create(op.get_bind())
    sa.Enum('PUBLIC', 'AUTHENTICATED', 'RESTRICTED', name='activitylocktype').create(op.get_bind())
    sa.Enum('SUBTYPE_DYNAMIC_PAGE', 'SUBTYPE_DYNAMIC_MARKDOWN', 'SUBTYPE_DYNAMIC_EMBED', 'SUBTYPE_VIDEO_YOUTUBE', 'SUBTYPE_VIDEO_HOSTED', 'SUBTYPE_DOCUMENT_PDF', 'SUBTYPE_DOCUMENT_DOC', 'SUBTYPE_ASSIGNMENT_ANY', 'SUBTYPE_CUSTOM', 'SUBTYPE_SCORM_12', 'SUBTYPE_SCORM_2004', name='activitysubtypeenum').create(op.get_bind())
    sa.Enum('TYPE_VIDEO', 'TYPE_DOCUMENT', 'TYPE_DYNAMIC', 'TYPE_ASSIGNMENT', 'TYPE_CUSTOM', 'TYPE_SCORM', name='activitytypeenum').create(op.get_bind())
    op.add_column('course', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('course', sa.Column('learnings', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('thumbnail_type', postgresql.ENUM('IMAGE', 'VIDEO', 'BOTH', name='thumbnail_type', create_type=False), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('thumbnail_video', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('course', sa.Column('seo', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('course_uuid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('course', sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('course', sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('thumbnail_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('course', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('course', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('open_to_contributors', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('course_org_id_fkey'), 'course', 'organization', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_course_org_public_published_created'), 'course', ['org_id', 'public', 'published', 'creation_date'], unique=False)
    op.create_index(op.f('ix_course_org_id'), 'course', ['org_id'], unique=False)
    op.create_index(op.f('ix_course_course_uuid'), 'course', ['course_uuid'], unique=False)
    op.add_column('activity', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('activity', sa.Column('lock_type', postgresql.ENUM('PUBLIC', 'AUTHENTICATED', 'RESTRICTED', name='activitylocktype', create_type=False), autoincrement=False, nullable=False))
    op.add_column('activity', sa.Column('current_version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('activity', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('activity', sa.Column('activity_sub_type', postgresql.ENUM('SUBTYPE_DYNAMIC_PAGE', 'SUBTYPE_DYNAMIC_MARKDOWN', 'SUBTYPE_DYNAMIC_EMBED', 'SUBTYPE_VIDEO_YOUTUBE', 'SUBTYPE_VIDEO_HOSTED', 'SUBTYPE_DOCUMENT_PDF', 'SUBTYPE_DOCUMENT_DOC', 'SUBTYPE_ASSIGNMENT_ANY', 'SUBTYPE_CUSTOM', 'SUBTYPE_SCORM_12', 'SUBTYPE_SCORM_2004', name='activitysubtypeenum', create_type=False), autoincrement=False, nullable=False))
    op.add_column('activity', sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('activity', sa.Column('activity_type', postgresql.ENUM('TYPE_VIDEO', 'TYPE_DOCUMENT', 'TYPE_DYNAMIC', 'TYPE_ASSIGNMENT', 'TYPE_CUSTOM', 'TYPE_SCORM', name='activitytypeenum', create_type=False), autoincrement=False, nullable=False))
    op.add_column('activity', sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('activity', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('activity', sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('activity', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('activity', sa.Column('activity_uuid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('activity', sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('activity', sa.Column('last_modified_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('activity', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('activity_last_modified_by_id_fkey'), 'activity', 'user', ['last_modified_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('activity_org_id_fkey'), 'activity', 'organization', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('activity_course_id_fkey'), 'activity', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_activity_org_id'), 'activity', ['org_id'], unique=False)
    op.create_index(op.f('ix_activity_course_id'), 'activity', ['course_id'], unique=False)
    op.create_index(op.f('ix_activity_activity_uuid'), 'activity', ['activity_uuid'], unique=False)
    op.create_table('activityversion',
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('activityversion_activity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('activityversion_created_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('activityversion_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('activityversion_pkey'))
    )
    op.create_table('chapteractivity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('activity_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('chapteractivity_activity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('chapteractivity_chapter_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('chapteractivity_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('chapteractivity_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chapteractivity_pkey')),
    sa.UniqueConstraint('chapter_id', 'activity_id', name=op.f('uq_chapteractivity_chapter_activity'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_chapteractivity_org_id'), 'chapteractivity', ['org_id'], unique=False)
    op.create_index(op.f('ix_chapteractivity_course_id'), 'chapteractivity', ['course_id'], unique=False)
    op.create_index(op.f('ix_chapteractivity_chapter_id'), 'chapteractivity', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_chapteractivity_activity_id'), 'chapteractivity', ['activity_id'], unique=False)
    op.create_table('certificateuser',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('certification_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_certification_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], name=op.f('certificateuser_certification_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('certificateuser_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('certificateuser_pkey'))
    )
    op.create_index(op.f('ix_certificateuser_user_certification_uuid'), 'certificateuser', ['user_certification_uuid'], unique=True)
    op.create_table('chapter',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lock_type', postgresql.ENUM('PUBLIC', 'AUTHENTICATED', 'RESTRICTED', name='locktype', create_type=False), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chapter_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('chapter_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('chapter_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chapter_pkey'))
    )
    op.create_index(op.f('ix_chapter_org_id'), 'chapter', ['org_id'], unique=False)
    op.create_index(op.f('ix_chapter_course_id'), 'chapter', ['course_id'], unique=False)
    op.create_index(op.f('ix_chapter_chapter_uuid'), 'chapter', ['chapter_uuid'], unique=False)
    op.create_table('assignment',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('grading_type', postgresql.ENUM('ALPHABET', 'NUMERIC', 'PERCENTAGE', 'PASS_FAIL', 'GPA_SCALE', name='gradingtypeenum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('auto_grading', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('anti_copy_paste', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('show_correct_answers', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('allow_retries', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assignment_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('assignment_activity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('assignment_chapter_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('assignment_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('assignment_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assignment_pkey'))
    )
    op.create_index(op.f('ix_assignment_org_id'), 'assignment', ['org_id'], unique=False)
    op.create_index(op.f('ix_assignment_course_id'), 'assignment', ['course_id'], unique=False)
    op.create_index(op.f('ix_assignment_assignment_uuid'), 'assignment', ['assignment_uuid'], unique=False)
    op.create_table('assignmenttask',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hint', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reference_file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assignment_type', postgresql.ENUM('FILE_SUBMISSION', 'QUIZ', 'FORM', 'CODE', 'SHORT_ANSWER', 'NUMBER_ANSWER', 'OTHER', name='assignmenttasktypeenum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('contents', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('max_grade_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assignment_task_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('assignmenttask_activity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], name=op.f('assignmenttask_assignment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('assignmenttask_chapter_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('assignmenttask_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('assignmenttask_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assignmenttask_pkey'))
    )
    op.create_table('course_embedding',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('block_uuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chapter_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('course_embedding_activity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('course_embedding_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('course_embedding_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('course_embedding_pkey'))
    )
    op.create_index(op.f('ix_course_embedding_org_id'), 'course_embedding', ['org_id'], unique=False)
    op.create_index(op.f('ix_course_embedding_course_id'), 'course_embedding', ['course_id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('certification_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('certifications_course_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('certifications_pkey')),
    sa.UniqueConstraint('certification_uuid', name=op.f('certifications_certification_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('courseupdate',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('courseupdate_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('linked_activity_uuids', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('courseupdate_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('courseupdate_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('courseupdate_pkey'))
    )
    op.create_index(op.f('ix_courseupdate_org_id'), 'courseupdate', ['org_id'], unique=False)
    op.create_index(op.f('ix_courseupdate_courseupdate_uuid'), 'courseupdate', ['courseupdate_uuid'], unique=False)
    op.create_index(op.f('ix_courseupdate_course_id'), 'courseupdate', ['course_id'], unique=False)
    op.create_table('collectioncourse',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('collectioncourse_collection_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('collectioncourse_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('collectioncourse_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('collectioncourse_pkey'))
    )
    op.create_table('coursechapter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('coursechapter_chapter_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('coursechapter_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('coursechapter_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('coursechapter_pkey'))
    )
    op.create_index(op.f('ix_coursechapter_course_id'), 'coursechapter', ['course_id'], unique=False)
    op.create_index(op.f('ix_coursechapter_chapter_id'), 'coursechapter', ['chapter_id'], unique=False)
    op.create_table('block',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('block_type', postgresql.ENUM('BLOCK_QUIZ', 'BLOCK_VIDEO', 'BLOCK_DOCUMENT_PDF', 'BLOCK_IMAGE', 'BLOCK_AUDIO', 'BLOCK_CUSTOM', name='blocktypeenum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('block_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('block_activity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('block_chapter_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('block_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('block_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('block_pkey'))
    )
    op.create_table('assignmentusersubmission',
    sa.Column('submission_status', postgresql.ENUM('PENDING', 'SUBMITTED', 'GRADED', 'LATE', 'NOT_SUBMITTED', name='assignmentusersubmissionstatus', create_type=False), autoincrement=False, nullable=False),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overall_feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attempt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assignmentusersubmission_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], name=op.f('assignmentusersubmission_assignment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('assignmentusersubmission_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assignmentusersubmission_pkey'))
    )
    op.create_table('assignmenttasksubmission',
    sa.Column('assignment_task_submission_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_submission', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_submission_grade_feedback', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assignment_type', postgresql.ENUM('FILE_SUBMISSION', 'QUIZ', 'FORM', 'CODE', 'SHORT_ANSWER', 'NUMBER_ANSWER', 'OTHER', name='assignmenttasktypeenum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assignment_task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('assignmenttasksubmission_activity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignment_task_id'], ['assignmenttask.id'], name=op.f('assignmenttasksubmission_assignment_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('assignmenttasksubmission_chapter_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('assignmenttasksubmission_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('assignmenttasksubmission_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assignmenttasksubmission_pkey'))
    )
    # ### end Alembic commands ###
