"""remove_state_hydration_columns

Revision ID: 9929a5bb7e0a
Revises: daf704c4dd2b
Create Date: 2026-07-09 22:23:20.453243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9929a5bb7e0a'
down_revision: Union[str, None] = 'daf704c4dd2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'time_remaining_seconds')
    op.drop_column('assessment', 'saved_answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('saved_answers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('assessment', sa.Column('time_remaining_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
