"""restore ai tutoring sessions

Revision ID: 9e1b4717ba6b
Revises: a245cbc7aa92
Create Date: 2026-06-09 02:01:02.951863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '9e1b4717ba6b'
down_revision: Union[str, None] = 'a245cbc7aa92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tutoring_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('struggle_area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scaffolding_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tutoring_sessions_student_id'), 'ai_tutoring_sessions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tutoring_sessions_student_id'), table_name='ai_tutoring_sessions')
    op.drop_table('ai_tutoring_sessions')
    # ### end Alembic commands ###
