"""assessment_engine_features

Revision ID: a1b2c3d4e5f7
Revises: 
Create Date: 2026-07-01 13:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('difficulty_tier', sa.Integer(), nullable=True))
    # Provide a default value for existing rows
    op.execute('UPDATE campaign SET difficulty_tier = 1')
    op.alter_column('campaign', 'difficulty_tier', nullable=False)

    op.add_column('campaign_module', sa.Column('is_remediation', sa.Boolean(), nullable=True))
    op.execute('UPDATE campaign_module SET is_remediation = FALSE')
    op.alter_column('campaign_module', 'is_remediation', nullable=False)

    op.add_column('assessment', sa.Column('cancelled_count', sa.Integer(), nullable=True))
    op.execute('UPDATE assessment SET cancelled_count = 0')
    op.alter_column('assessment', 'cancelled_count', nullable=False)

    op.add_column('assessment', sa.Column('last_score', sa.Integer(), nullable=True))
    
    op.add_column('assessment', sa.Column('total_marks', sa.Integer(), nullable=True))
    op.execute('UPDATE assessment SET total_marks = 50')
    op.alter_column('assessment', 'total_marks', nullable=False)

    op.add_column('assessment', sa.Column('time_allowed_mins', sa.Integer(), nullable=True))
    op.execute('UPDATE assessment SET time_allowed_mins = 30')
    op.alter_column('assessment', 'time_allowed_mins', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'time_allowed_mins')
    op.drop_column('assessment', 'total_marks')
    op.drop_column('assessment', 'last_score')
    op.drop_column('assessment', 'cancelled_count')
    op.drop_column('campaign_module', 'is_remediation')
    op.drop_column('campaign', 'difficulty_tier')
    # ### end Alembic commands ###
