"""add subtopics to modules

Revision ID: a245cbc7aa92
Revises: 3d0296c7bef6
Create Date: 2026-06-09 01:57:36.204504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a245cbc7aa92'
down_revision: Union[str, None] = '3d0296c7bef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_module', sa.Column('subtopics', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_module', 'subtopics')
    # ### end Alembic commands ###
