"""Add adaptive learning models

Revision ID: c690084f50ac
Revises: e6f7a8b9c0d1
Create Date: 2026-06-05 02:20:42.331111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'c690084f50ac'
down_revision: Union[str, None] = 'e6f7a8b9c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syllabus_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('content_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mastery_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['syllabus_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['syllabus_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('apitoken', 'token_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_apitoken_token_hash'), table_name='apitoken')
    op.create_index('ix_apitoken_token_prefix', 'apitoken', ['token_prefix'], unique=False)
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_index('ix_apitoken_token_prefix', table_name='apitoken')
    op.create_index(op.f('ix_apitoken_token_hash'), 'apitoken', ['token_hash'], unique=False)
    op.alter_column('apitoken', 'token_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_table('assessment_logs')
    op.drop_table('syllabus_nodes')
    # ### end Alembic commands ###
